FROM mcr.microsoft.com/dotnet/sdk:8.0 AS debug
WORKDIR /app
COPY src/cartservice.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet build -c Debug
EXPOSE 8086 8087
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "run", "watch", "--urls=http://0.0.0.0:8086"]